//  Bruno Rhafael Fonteles de Lima
//  Stony Brook SOLAR ID: 110126067
//// 	Description:  Compile the C
//source file by using gcc (or any other C compiler of your choice) through the system() function
//and then run the resulting program with the given input file. You will then compare the output
//file generated by the execution of this program with the expected result file to determine
//whether or not the program is correct.
//  HOMEWORK 3 - due Tuesday, March 24th no later than 5:00PM


#include <stdio.h>
#include <string.h>

#define LINES 5

// MAIN FUNCTION
int main (){
	
	char nameSource[30];
	char nameinput[30];
	char nameResult [30];
	char stringGcc [100] = "gcc -o Prog "; 
	char stringGcc1 [100] = "Prog ";
	char stringGcc2[100] = " > output.txt";
	int i;
	
	
	printf("Please enter the name of the source file: ");
	scanf("%s",nameSource);
		
	printf("Please enter the name of the input file: ");
	scanf("%s",nameinput);
	
	printf("Please enter the name of the expected result file: ");
	scanf("%s",nameResult);
	
	system(strcat(stringGcc,nameSource));
	system(strcat(strcat(stringGcc1,nameinput),stringGcc2));
	
	FILE *output, *results;
	
	output = fopen("output.txt","r");
	if(output == NULL){
	
		printf("Error Reading File");
		return 1;
		}
	
	
	results = fopen(nameResult,"r");
	if(results == NULL){
	
		printf("Error Reading File");
		return 1;
		}
	
	char string[60];
	char string2[60];
	int fail = 0;
	
	for(i=0; i<LINES; i++){
		
		fscanf(output,"%s\n",string);
		fscanf(results,"%s\n",string2);
		
		if(strcmp(string,string2)!= 0){
			fail++;
		}
		
	}
	
	if(fail == 0){
		printf("The output of the program is correct.");
	}
	else printf("The output of the program is not correct.");
	
	fclose(output);
	fclose(results);
	
			
	return 0;
}


