# Bruno Rhafael Fonteles de Lima
# 110126067

hw4: main.o functions.o Hit.o
	     g++ -o hw4 main.o functions.o Hit.o

main.o: main.cpp hit.h
		g++ -c main.cpp
		
functions.o: functions.cpp 
		g++ -c functions.cpp
Hit.o: Hit.cpp hit.h
		g++ -c Hit.cpp
		
		