# Bruno Rhafael Fonteles de Lima
# 110126067

HW5: main.o ListRecords.o BookRecord.o
	     g++ -o HW5 main.o ListRecords.o BookRecord.o

main.o: main.cpp BookRecord.h ListRecords.h
		g++ -c main.cpp
		
ListRecords.o: ListRecords.cpp 
		g++ -c ListRecords.cpp
		
BookRecord.o: BookRecord.cpp BookRecord.h
		g++ -c BookRecord.cpp

		
		