//  Bruno Rhafael Fonteles de Lima
//  Stony Brook SOLAR ID: 110126067
//// 	Description:  Compile the C
//source file by using gcc (or any other C compiler of your choice) through the system() function
//and then run the resulting program with the given input file. You will then compare the output
//file generated by the execution of this program with the expected result file to determine
//whether or not the program is correct.
//  HOMEWORK 3 - due Tuesday, March 24th no later than 5:00PM
// COMPILER: MinGW GCC 4.8.1


#include <stdio.h>
#include <string.h>
#include "functions.c"



// MAIN FUNCTION
int main (){
	
	char nameSource[30];  // Name of the program : myprog1 or myProg2
	char nameinput[30];  // Name of the input file
	char nameResult [30]; // name of the results file to be compared  with the output file
	
	
	
	printf("Please enter the name of the source file: ");
	scanf("%s",nameSource);
		
	printf("Please enter the name of the input file: ");
	scanf("%s",nameinput);
	
	printf("Please enter the name of the expected result file: ");
	scanf("%s",nameResult);
	
	callSystem(nameSource,nameinput); // Call of the function callSystem
	
	generateFile(nameResult); // Call of the function generateFile
	
			
	return 0;
}


